//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotifyBattery.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NotifyBattery.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Battery0 {
            get {
                object obj = ResourceManager.GetObject("Battery0", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Battery1 {
            get {
                object obj = ResourceManager.GetObject("Battery1", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Battery2 {
            get {
                object obj = ResourceManager.GetObject("Battery2", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Battery3 {
            get {
                object obj = ResourceManager.GetObject("Battery3", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon BatteryC {
            get {
                object obj = ResourceManager.GetObject("BatteryC", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon BatteryF {
            get {
                object obj = ResourceManager.GetObject("BatteryF", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by hmovaghari↵http://hmovaghari.rozblog.com.
        /// </summary>
        internal static string CreatedBY {
            get {
                return ResourceManager.GetString("CreatedBY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Function when disconnect from Adapter.
        /// </summary>
        internal static string STRActionFUN {
            get {
                return ResourceManager.GetString("STRActionFUN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NotifyBattery.
        /// </summary>
        internal static string STRAppName {
            get {
                return ResourceManager.GetString("STRAppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery is Low Level, Please connect to Adapter.
        /// </summary>
        internal static string STRChargeNeed {
            get {
                return ResourceManager.GetString("STRChargeNeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battery is High Level, Please disconnect from Adapter.
        /// </summary>
        internal static string STRChargeUnneed {
            get {
                return ResourceManager.GetString("STRChargeUnneed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charging .
        /// </summary>
        internal static string STRCharging {
            get {
                return ResourceManager.GetString("STRCharging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Data.
        /// </summary>
        internal static string STRInvalidData {
            get {
                return ResourceManager.GetString("STRInvalidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Charge for disconnect from Adapter.
        /// </summary>
        internal static string STRMaxCharge {
            get {
                return ResourceManager.GetString("STRMaxCharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum Charge for connect to  Adapter.
        /// </summary>
        internal static string STRMinCharge {
            get {
                return ResourceManager.GetString("STRMinCharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % Remaining.
        /// </summary>
        internal static string STRRemaining {
            get {
                return ResourceManager.GetString("STRRemaining", resourceCulture);
            }
        }
    }
}
